llvm/oneapi: fixes to bring pmix up to iso c99
compliance at least as far as the LLVM on which the Intel OneAPI 2022
release is based (14).  LLVM is getting pickier about what it lets
through in terms of ISO C99 compliance when using -Werror, etc.

Related to https://reviews.llvm.org/D122983

Without this patch and without disabling developer flags (which is very
difficult when building within spack without adding yet another variant)
one gets these sorts of errors at compile time.

pmix_net.c:168:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

threads/thread.c:109:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int pmix_tsd_keys_destruct()
                          ^
                           void

base/bfrop_base_frame.c:68:13: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]
        int count = 0;

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>